[workspace]

members = [
  "abstract_factory",
  "builder",
  "factory_method/maze_game",
  "factory_method/render_dialog",
  "prototype",
  "simple_factory",
  "singleton",
  "static_creation_method",
]
