[workspace]

members = [
  "creational/abstract-factory",
  "creational/factory-method/maze-game",
  "creational/factory-method/render-dialog",
  "creational/prototype",
  "creational/simple-factory",
  "creational/singleton",
  "creational/static-creation-method",
]
